--< Written by: Christopher Gholmieh
--< Variables (Assignment):

--< Utilities:
local function is_windows_operating_system()
    return package.config:sub(1, 1) == "\\"
end

--< Functions:
local function download_repository()
    --< Variables (Assignment):
    --< Repository:
    local GITHUB_REPOSITORY = "https://github.com/BurnySc2/python-sc2"

    --< Logic:
    os.execute("git clone " .. GITHUB_REPOSITORY .. " ./generator/python-sc2")
end

local function process_files()
    --< Variables (Assignment):
    --< Repository:
    local REPOSITORY_PATH = "./generator/python-sc2"

    --< Identifier:
    local IDENTIFIER_PATH = REPOSITORY_PATH .. "/sc2/ids/"

    --< Files:
    local IDENTIFIER_FILES = {
        --< Ability:
        ["ability_id.py"] = "ABILITY_IDENTIFIER";

        --< Upgrade:
        ["upgrade_id.py"] = "UPGRADE_IDENTIFIER";

        --< Effect:
        ["effect_id.py"] = "EFFECT_IDENTIFIER";

        --< Unit:
        ["unit_typeid.py"] = "UNIT_IDENTIFIER";

        --< Buff:
        ["buff_id.py"] = "BUFF_IDENTIFIER";
    }

    --< Logic:
    for identifier_file, dictionary_name in pairs(IDENTIFIER_FILES) do
        --< Variables (Assignment):
        --< Path:
        local identifier_file_path = IDENTIFIER_PATH .. identifier_file

        --< File:
        local __identifier_file = assert(io.open(identifier_file_path, "r"))

        --< Configuration:
        local configuration_file = identifier_file:gsub(".py", ".lua")

        --< Contents:
        local contents = {
            "--< Autogenerated by: generator/generate-identifiers.lua";
            "--< Credit: BurnySC2";
            "";
            "--< Variables (Assignment):";
            "--< Utilities:";
            "local Enumeration = require(\"source.utilities.enumeration\")";
            "";
            "--< Enumerations:";
            string.format("local %s = {", dictionary_name);
        }

        --< Terminators:
        local terminators = {
            "}";
            "";
            "--< Identifiers:";
            string.format("return %s", dictionary_name);
        }

        --< Processing:
        for line in __identifier_file:lines() do
            --< Variables (Assignment):
            --< Contents:
            local key, value = line:match("([%w_]+)%s*=%s*(%d+)")

            if not key then
                goto continue
            end

            --< Logic:
            table.insert(contents, string.format("    %s = Enumeration.new(\"%s\", %d);", key, key, tonumber(value)));
            
            --< Continue:
            ::continue::
        end

        for _, terminator in ipairs(terminators) do
            table.insert(contents, terminator)
        end

        --< File:
        __identifier_file:close()

        --< Variables (Assignment):
        --< File:
        __identifier_file = assert(io.open("./source/identifiers/" .. configuration_file, "w"))

        --< Logic:
        for iterator, line in ipairs(contents) do
            if iterator == #contents then
                __identifier_file:write(line)
            else
                __identifier_file:write(line .. "\n")
            end
        end

        --< File:
        __identifier_file:close()
    end
end

local function remove_repository()
    --< Variables (Assignment):
    --< Repository:
    local REPOSITORY_PATH = "\"./generator/python-sc2\""

    --< Command:
    local command

    if is_windows_operating_system() then
        command = "rmdir /S /Q " .. REPOSITORY_PATH
    else
        command = "rm -rf " .. REPOSITORY_PATH
    end

    --< Logic:
    os.execute(command)
end


--< Program:
download_repository()
process_files()
remove_repository()